# version: "3.8"

# Run:
# docker-compose up --build -d

# Stop:
# docker-compose down

volumes:
  rabbitmq_data:
    name: parker_rabbitmq_data

networks:
  parker-net:
    driver: bridge
    name: parker-net

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: parker-rabbit
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - parker-net

  rabbitmq-sendnotification:
    build:
      context: .
      dockerfile: ./sendnotification/Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - parker-net

  staff:
    build:
      context: .
      dockerfile: ./staff/Dockerfile
    env_file:
      - .env
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
    networks:
      - parker-net

  guest:
    build:
      context: .
      dockerfile: ./guest/Dockerfile
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    networks:
      - parker-net

  accesslogs:
    build:
      context: .
      dockerfile: ./accesslogs/Dockerfile
    env_file:
      - .env
    ports:
      - "8084:8084"
    depends_on:
      - rabbitmq
    networks:
      - parker-net

  error:
    build:
      context: .
      dockerfile: ./error/Dockerfile
    env_file:
      - .env
    ports:
      - "8078:8078"
    depends_on:
      - rabbitmq
    networks:
      - parker-net

  emailservice:
    build:
      context: .
      dockerfile: ./emailservice/Dockerfile
    env_file:
      - .env
    ports:
      - "8088:8088"
    depends_on:
      - rabbitmq
    networks:
      - parker-net

  stripeservice:
    build:
      context: .
      dockerfile: ./stripeservice/Dockerfile
    env_file:
      - .env
    ports:
      - "8086:8086"
    depends_on:
      - rabbitmq
    networks:
      - parker-net

  testlock:
    build:
      context: .
      dockerfile: ./testlock/Dockerfile
    env_file:
      - .env
    ports:
      - "8077:8077"
    depends_on:
      - rabbitmq
    networks:
      - parker-net

  enterpark:
    build:
      context: .
      dockerfile: ./enterpark/Dockerfile
    env_file:
      - .env
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
    networks:
      - parker-net

  telegramservice:
    build:
      context: .
      dockerfile: ./telegramservice/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - parker-net

  makepayment:
    build:
      context: .
      dockerfile: ./makepayment/Dockerfile
    env_file:
      - .env
    ports:
      - "8087:8087"
    depends_on:
      - rabbitmq
    networks:
      - parker-net

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8100:8100"
    networks:
      - parker-net
