# Use a base image with Python
FROM python:3.9-slim

# Install Cloudflare Tunnel
RUN apt-get update && apt-get install -y wget \
    && wget https://github.com/cloudflare/cloudflared/releases/download/2025.2.1/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared \
    && chmod +x /usr/local/bin/cloudflared \
    && apt-get clean

# # Set environment variables for Google Cloud credentials (if applicable)
# ENV GOOGLE_APPLICATION_CREDENTIALS=/app/esdlocking.json

# Install Python dependencies
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

# Copy your Python app files into the container
COPY . /app

# Install supervisord to manage multiple processes
RUN apt-get update && apt-get install -y supervisor

# Copy the supervisord configuration
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Expose the port your app will run on
EXPOSE 8081

# Start the supervisor process
CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
