volumes:
  rabbitmq_data:
    name: parker_rabbitmq_data

networks:
  parker-net:
    driver: bridge
    name: parker-net

services:

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: parker-rabbit
    restart: always
    ports:
      - "8078:8078"
      - "5672:5672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - parker-net